CASMSEC-385: kyverno resources need to be adjusted
Cray-HPE/cray-kyverno pull request #7
Opened 2023-02-20 08:27 UTC by pradeepkumargl

## Summary and Scope

We noticed on Surtur system that the CPU and Memory utilization for Kyverno pods has reached around 2.3 times of CPU requests and 4 times of memory limit.(Crossed the max limit)

Taking into consideration of higher configuration systems with future Kyverno rule increment and number of pods associated with that, we have increased CPU requests to 5 times and memory limit to 4 times to the current values.

## Test description

Changed the values of Memory and CPU limits.

### Tested on:

SURTUR system

### Testing:

Before:
apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: cray-kyverno
      meta.helm.sh/release-namespace: kyverno
    creationTimestamp: "2022-11-02T05:17:39Z"
    generation: 1
    labels:
      app: kyverno
      app.kubernetes.io/component: kyverno
      app.kubernetes.io/instance: cray-kyverno
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kyverno
      app.kubernetes.io/part-of: kyverno
      app.kubernetes.io/version: v2.3.3
      helm.sh/chart: kyverno-v2.3.3
    name: cray-kyverno
    namespace: kyverno
    resourceVersion: "135910984"
    uid: a602307f-8187-4cc0-83c8-de1fc881e6ee
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: cray-kyverno
        app.kubernetes.io/name: kyverno
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 40%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: kyverno
          app.kubernetes.io/component: kyverno
          app.kubernetes.io/instance: cray-kyverno
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: kyverno
          app.kubernetes.io/part-of: kyverno
          app.kubernetes.io/version: v2.3.3
          helm.sh/chart: kyverno-v2.3.3
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - kyverno
                topologyKey: kubernetes.io/hostname
              weight: 1
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - kyverno
              topologyKey: kubernetes.io/hostname
        containers:
        - env:
          - name: INIT_CONFIG
            value: cray-kyverno
          - name: METRICS_CONFIG
            value: cray-kyverno-metrics
          - name: KYVERNO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: KYVERNO_SVC
            value: cray-kyverno-svc
          - name: KYVERNO_DEPLOYMENT
            value: cray-kyverno
          image: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyverno:v1.6.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /health/liveness
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: kyverno
          ports:
          - containerPort: 9443
            name: https
            protocol: TCP
          - containerPort: 8000
            name: metrics-port
            protocol: TCP
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /health/readiness
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        initContainers:
        - env:
          - name: METRICS_CONFIG
            value: cray-kyverno-metrics
          - name: KYVERNO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: KYVERNO_DEPLOYMENT
            value: cray-kyverno
          image: artifactory.algol60.net/csm-docker/stable/ghcr.io/kyverno/kyvernopre:v1.6.2
          imagePullPolicy: IfNotPresent
          name: kyverno-pre
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        priorityClassName: csm-high-priority-service
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: cray-kyverno
        serviceAccountName: cray-kyverno
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2022-11-02T05:17:39Z"
      lastUpdateTime: "2022-11-02T05:18:56Z"
      message: ReplicaSet "cray-kyverno-6fd946bf9f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-11-07T20:14:05Z"
      lastUpdateTime: "2022-11-07T20:14:05Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
ncn-m001:~ #

After:

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: cray-kyverno
    meta.helm.sh/release-namespace: kyverno
  creationTimestamp: "2022-11-02T05:17:39Z"
  generation: 2
  labels:
    app: kyverno
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: cray-kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v2.3.3
    helm.sh/chart: kyverno-v2.3.3
  name: cray-kyverno
  namespace: kyverno
  resourceVersion: "148898666"
  uid: a602307f-8187-4cc0-83c8-de1fc881e6ee
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: cray-kyverno
      app.kubernetes.io/name: kyverno
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 40%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kyverno
        app.kubernetes.io/component: kyverno
        app.kubernetes.io/instance: cray-kyverno
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kyverno
        app.kubernetes.io/part-of: kyverno
        app.kubernetes.io/version: v2.3.3
        helm.sh/chart: kyverno-v2.3.3
    spec:
      affinity:
        po [...]

2023-02-20 08:28 UTC, pradeepkumargl commented
![beforeMEMORY](https://user-images.githubusercontent.com/80017325/220052375-bc20c61c-7544-4e6e-a22e-e82c006048a8.png)
![AfterCPU](https://user-images.githubusercontent.com/80017325/220052383-20575596-7e7a-4d83-997b-04b734dd8254.png)
![AfterMEMORY](https://user-images.githubusercontent.com/80017325/220052385-532d1b9d-640b-41ec-9e76-3a5947756dd1.png)
![beforeCPU](https://user-images.githubusercontent.com/80017325/220052389-d8b57d03-0ffe-4539-bdbb-0e07f6644792.png)

2023-02-20 08:29 UTC, pradeepkumargl commented
The screen shots from grafana dashboard for Kyverno pods are attached with and without changes.

2023-02-21 16:12 UTC, jeremy-duckworth requested changes
See updated metrics in Slack thread on topic.

2023-02-22 18:04 UTC, kimjensen-hpe approved these changes

2023-02-22 19:02 UTC, jeremy-duckworth approved these changes

2023-02-23 03:32 UTC, merged